## Copyright(c) 2010 ~ 2013 Siliconarts, Inc. All Rights Reserved
## tutorials
## Date : 

#-------------------------------------------------
# Project
#-------------------------------------------------
SRC_PATH		:= $(PWD)
TARGETNAME		:= rc_chess

SRCS			:= \
	$(SRC_PATH)/../common/SceneData.cpp \
	$(SRC_PATH)/main.cpp

#-------------------------------------------------
# common config
#-------------------------------------------------
include ../config.common
