## Copyright(c) 2010 ~ 2013 Siliconarts, Inc. All Rights Reserved
## makefiles
## Date :

all:
	cd RCFramework;				$(MAKE) -f Makefile;		cd ..

	cd boat;				$(MAKE) -f Makefile;		cd ..
	cd car;				$(MAKE) -f Makefile;		cd ..
	cd crown;				$(MAKE) -f Makefile;		cd ..
	cd museum;				$(MAKE) -f Makefile;		cd ..
	cd museum-01;				$(MAKE) -f Makefile;		cd ..
	cd shuttle;				$(MAKE) -f Makefile;		cd ..
	cd teapot;				$(MAKE) -f Makefile;		cd ..
	cd violinCase;				$(MAKE) -f Makefile;		cd ..
	cd chess;				$(MAKE) -f Makefile;		cd ..
	cd geometry;				$(MAKE) -f Makefile;		cd ..
    
	cd geometry-01;				$(MAKE) -f Makefile;		cd ..	
	


clean:
	cd RCFramework;				$(MAKE) -f Makefile clean;	cd ..

	cd boat;				$(MAKE) -f Makefile clean;	cd ..
	cd car;					$(MAKE) -f Makefile clean;	cd ..
	cd crown;				$(MAKE) -f Makefile clean;	cd ..
	cd museum;				$(MAKE) -f Makefile clean;	cd ..
	cd museum-01;				$(MAKE) -f Makefile clean;	cd ..	
	cd shuttle;				$(MAKE) -f Makefile clean;	cd ..
	cd teapot;				$(MAKE) -f Makefile clean;	cd ..
	cd violinCase;				$(MAKE) -f Makefile clean;	cd ..
	cd chess;				$(MAKE) -f Makefile clean;	cd ..
	cd geometry;				$(MAKE) -f Makefile clean;	cd ..
	cd geometry-01;				$(MAKE) -f Makefile clean;	cd ..

	
	
